version: "3.9"
services:
  backend:
    build:
      context: .
      target: runtime
    ports:
      - "8000:8000"
    environment:
        - DATABASE_URL=sqlite:////application/app.db
    volumes:
      - ./app.db:/application/app.db
  tests:
    build:
      context: .
      target: tests
    environment:
      - DATABASE_URL=sqlite:///testdb.db
